<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Karthick" name="run package" tests="8" failures="1" timestamp="26 Aug 2020 15:17:51 GMT" time="5.395" errors="0">
  <testcase name="b_m1" time="1.984" classname="com.testng.basics.AnnotatinSample">
    <failure type="java.lang.AssertionError" message="expected [Category name is already exist. please entesdsdr new category name] but found [Category name is already exist. please enter new category name]">
      <![CDATA[java.lang.AssertionError: expected [Category name is already exist. please entesdsdr new category name] but found [Category name is already exist. please enter new category name]
	at com.testng.basics.AnnotatinSample.b_m1(AnnotatinSample.java:48)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- b_m1 -->
  <testcase name="c_m3" time="0.0" classname="com.testng.basics.AnnotatinSample"/>
  <testcase name="m4" time="0.004" classname="com.testng.basics.AnnotatinSample"/>
  <testcase name="a_m2" time="0.294" classname="com.testng.basics.AnnotatinSample"/>
  <testcase name="c_m1" time="0.001" classname="com.testng.basics.AnnotatinSample2"/>
  <testcase name="c_m3" time="0.001" classname="com.testng.basics.AnnotatinSample2"/>
  <testcase name="m2" time="0.001" classname="com.testng.basics.AnnotatinSample2"/>
  <testcase name="m4" time="0.002" classname="com.testng.basics.AnnotatinSample2"/>
</testsuite> <!-- run package -->
